services:
  mysql:
    image: mysql:8
    container_name: bit-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=5776
      - MYSQL_DATABASE=bitcomputer
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: bit-redis
    ports:
      - "6379:6379"

volumes:
  mysql-data: