services:
  mysql:
    image: mysql:8
    container_name: bit-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Dd905925@
      - MYSQL_DATABASE=bitcomputer
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: bit-redis
    ports:
      - "6379:6379"

  arangodb:
    image: arangodb:latest
    container_name: bit-arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=Dd905925@
    ports:
      - "8529:8529"
    volumes:
      - arango-data:/var/lib/arangodb3

volumes:
  mysql-data:
  arango-data: