spring.application.name=BitComputer

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3307/bitcomputer?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password= #own password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
#spring.data.redis.password= password

# JWT Configuration
jwt.secret=BitComputerSecretKeyForJWTTokenGenerationAndValidationMustBeLongEnough
